"""
PrP reference sequences for PRNP-OrthoMiner.
Sequences stored as uppercase nucleotide strings without whitespace.
"""

GROUPS_ORDER = [
    "Roedores", "Murciélagos", "Primates",
    "Marsupiales", "Artiodáctilos", "Carnívoros", "Lagomorfos", "Otros"
]

PRP_SEQUENCES = {
    # ── Roedores ────────────────────────────────────────────
    "Ardilla de tierra PrP": {
        "group": "Roedores",
        "sequence": (
            "ATGGTGAACCCTGGCTGCTGGCTGCTGGTTCTCTTCGTGGCCACATTGAGTGACGTCGGCCTCTGCAAAAAACGGCCAAA"
            "GCCTGGAGGAGGGTGGAACACTGGAGGAAGCCGTTACCCTGGGCAAGGCAGCCCTGGAGGCAACCGCTACCCACCTCAGG"
            "GTGGTGGCTGGGGGCAGCCTCATGGTGGTGGAGGCTGGGGGCAACCCCATGGTGGCGGTGGCTGGGGACAACCCCACGGT"
            "GGTGGTTGGGGTCAGGGTGGCACCCATAATCAATGGGGCAAGCCCGTTAAGCCAAAAACCAGCATGAAGCATGTGGCAGG"
            "TGCTGCTGCAGCCGGGGCAGTGGTAGGGGGCCTTGGTGGCTACATGCTGGGGAGTGCCATGAGCAGGCCCATGATGCACT"
            "TTGGCAATGACTATGAGGACCGTTACTACCGTGAAAACATGAACCGTTACCCCAGCCAAGTGTACTACAAGCCCGTGGAT"
            "CAGTATCCCAACCAGAACAGCTTTGTGCATGACTGTGTCAATATCACAATCAAGCAGCATACAACCACCACCACCACCAA"
            "AGGGGATAACTTCACCGAGACCGATATTAAGATAATGGAGCGTGTGGTGGAGCAGATGTGCACCACCCAGTACAAGCAGG"
            "AGGCCCAACAGGCTTACTACCCAAGAGGATCCAGCATGCTCCTCTTCTCCTCCCCACCTGTGATCCTCCTCATCTCCTTC"
            "CTCATTTTCCTGATTGTGGGATGA"
        )
    },
    "Ardilla PrP": {
        "group": "Roedores",
        "sequence": (
            "ATGAAAAAGCGACCAAAGCCTGGAGGAGGGTGGAACACTGGGGGAAGCCGTTACCCTGGGCAAGGCAGCCCTGGAGGCAA"
            "CCGCTACCCACCCCAAGGTGGTGGTGGCTGGGGGCAGCCTCATGGTGGTGGCTGGGGGCAACCCCATGGTGGCGGAGGTT"
            "GGGGGCAACCCCATGGTGGTGGTGGCTGGGGACAACCCCACGGTGGTGGCTGGGGGCAAGGAGGCACCCACAATCAATGG"
            "GGCAAGCCTAATAAGCCAAAAACCAACATGAAGCATGTGGCAGGTGCTGCTGCGGCTGGGGCAGTGGTGGGGGGCCTTGG"
            "TGGCTACATGCTGGGGAGTGCCATGAGCCGGCCCCTTATACATTTTGGCAACGACTATGAGGACCGTTACTACCGTGAAA"
            "ACATGTATCGTTACCCCAACCAAGTGTACTACAAGCCCGTGGATCAGTACAGCAACCAGAACAACTTTGTGCATGACTGC"
            "GTCAATATCACAGTCAAGCAGCACACAGTCACCACGACCACCAAAGGGGAGAACTTCACCGAGACCGACATTAAGATCAT"
            "GGAGCGCGTGGTGGAGCAGATGTGCATCACCCAGTACCAGCAGGAGGCCCAGGCTTACTATCAGAGAGGATCCAGCTGA"
        )
    },
    "Gerbil PrP": {
        "group": "Roedores",
        "sequence": (
            "ATGGCGAACCTTGGCTACTGGCTGCTGGCCCTCTTTGTGACCATGTGGACTGATGTGGGCCTCTGCAAGAAGCGGCCAAA"
            "GCCTGGAGGGTGGAACACTGGCGGGAGCCGGTACCCTGGGCAGGGAAGCCCTGGAGGCAACCGCTACCCTCCTCAGGGTG"
            "GTGGCTGGGGGCAGCCCCATGGTGGTGGCTGGGGGCAGCCCCATGGTGGGGGCTGGGGACAGCCTCATGGCGGGGGCTGG"
            "GGTCAGCCTCATGGCGGTGGCTGGGGTCAAGGAGGGGGCACCCACAGTCAGTGGAACAAGCCCAGCAAGCCAAAAACCAA"
            "CATGAAGCACGTGGCAGGTGCCGCTGCGGCTGGGGCCGTGGTGGGGGGCCTTGGCGGCTACATGTTGGGGAGCGCCATGA"
            "GCAGGCCCATGATCCACTTTGGCAACGACTGGGAGGACCGCTACTACCGTGAGAACATGTACCGCTACCCGAACCAGGTG"
            "TATTACAGGCCGGTGGACCAGTACAGCAACCAGAACAATTTCGTGCACGATTGCGTCAACATCACCATCAAGCAGCACAC"
            "GGTCACCACCACCACCAAGGGCGAGAACTTCACCGAGACAGACGTGAAGATGATGGAGCGCGTGGTGGAGCAGATGTGCG"
            "TCACCCAGTACCAGAAGGAGTCCCAGGCCTACTACGACGGAAGGCGGTCCAGCGCAGTGCTTTTCTCCTCCCCTCCCGTG"
            "ATCCTCCTCATCTCCTTCCTCCTCTTCCTGATAGTGGGA"
        )
    },
    "Rata PrP": {
        "group": "Roedores",
        "sequence": (
            "ATGGCAAACCTTAGCTACTGGCTGCTGGCACTCTTTGTGGCTACGTGGACTGATGTTGGCCTCTGCAAGAAGCGGCCAAA"
            "GCCTGGAGGGTGGAACCCTGGTGGAAGCCGATACCCCGGGCAGGGCAGCCCTGGAGGGAACCGTTACCCACCTCAGGGTG"
            "GTGGTGGCTGGGGGCAGCCCCATGGTGGCGGCGGCTGGGGGCAGCCCCATGGTGGCGGTGGCTGGGGGCAGCCCCATGGT"
            "GGCGGTGGCTGGGGGCAGCCCCATGGTGGCGGCGGCTGGGGTCAAGGAGGCAGCCACAGTCAGTGGAACAAGCCCAGTAA"
            "GCCAAAAACCAACATGAAGCAGATGGCAGGCGCTGCTGCAGCTGGGGCAGTGGTCGGGGGTCTTGGTGGCTACATGCTGG"
            "GGAGTGCCATGAGCAGGCCCATGATCCATTTTGGCAGCGACTGGGAGGACCGCTACTACCGTGAAAACATGTACCGTTAC"
            "CCCAACCAAGTGTACTACAGGCCAGTGGATCAGTACAGCAACCAGAACAACTTCGTGCACGACTGTGTCAATATCACGAT"
            "CAAGCAGCACACGGTCACCACCACCACCAAGGGGGAGAACTTCACGGAGACCGACGTCAAGATGATGGAGCGCGTGGTGG"
            "AGGAGATGTGTACCACCCAGTACCAGAAGGAGTCCCAGGCCTATTACGAAGGACGAAGATCCAGCGCGGTGCTCTTCTCC"
            "TCCCCTCCCGTGATCCTCCTCCTTTCCTTCCTCATCTTCCTGATAGTGGGATGA"
        )
    },
    "Rata topo PrP": {
        "group": "Roedores",
        "sequence": (
            "TGGCAAACCTTGGCTACTGGCTGCTCCTCCTCTTTGTGGCCACGTGGAGTGACATTGGCCTCTGCAAGAAGCGGCACAAG"
            "CCTGGAGGGTGGAACACTGGTGGAAGCCGATACCCTGGACAAGGCAGCCCTGGAGGCAACCGTTACCCACCGCAGGGTGG"
            "CGGCACCTGGGGGCAGCCTCATGGTGGTGGTGGCTGGGGACAGCCCCATGGTGGTGGTGGCTGGGGACAGCCCCATGGTG"
            "GTGGTGGCTGGGGACAGCCCCATGGTGGTGGTGGCTGGGGTCAAGGAGGGAGCACTCACTGGAACAAACCCAGTAAGCCA"
            "AAAACCAACATGAAGCATGTGGCAGGTGCTGCCGCAGCTGGGGCAGTAGTAGGGGGCCTTGGTGGCTACATGCTGGGAAG"
            "TGCCATGAGCAGGCCCCTCATCCATTTTGGCAATGACTATGAGGATCGTTACTACCGGGAAAACATGTACCGTTACCCCA"
            "ACCAAGTATACTACAGGCCTGTGGATCAGTACAACAACCAGAACAACTTTGTGCACGACTGTGTCAATATCACGGTCAAG"
            "CAGCACACAGTTACCACCACTACCAAGGGGGAGAACTTCACTGAGACCGACATCAAGATGATGGAGCGTGTGGTGGAACA"
            "GATGTGCATCACCCAGTACCAGAAGGAGTCTCAGGCCTATTACGATGGAAGAAGATCCAGTGCAGTGCTCTTCTCCTCCC"
            "CTCCTATGATCCTTCTCATCTCCTTCCTCATCTTCCTGATAGTGGGATGA"
        )
    },
    "Ratón ciervo PrP": {
        "group": "Roedores",
        "sequence": (
            "ATGAAGAAGCGGCCAAAGCCTGGAGGCTGGAACACCGGTGGAAGCCGATACCCTGGGCAGGGCAGCCCTGGGGGCAACCG"
            "TTACCCACCTCAGGGTGGCGGCACCTGGGGGCAGCCCCATGGTGGTGGCTGGGGGCAGCCCCATGGTGGTGGCTGGGGAC"
            "AACCTCATGGTGGTGGCTGGGGGCAGCCCCATGGTGGTGGCTGGGGTCAAGGAGGCGGCACCCACAATCAGTGGAACAAG"
            "CCCAGCAAGCCAAAAACCAACATGAAGCATGTGGCAGGCGCTGCTGCGGCTGGGGCAGTGGTGGGGGGCCTTGGTGGCTA"
            "CATGCTGGGGAGCGCCATGAGCAGGCCCATGATCCATTTTGGCAATGACTGGGAGGACCGCTACTACCGCGAAAACATGA"
            "ACCGTTACCCTAACCAAGTGTACTATCGGCCCGTGGATCAGTACAACAATCAGAACAACTTCGTGCACGATTGCGTCAAT"
            "ATCACCATCAAGCAGCACACAGTCACCACCACCACCAAGGGGGAGAACTTCACGGAGACCGACGTCAAGATGATGGAGCG"
            "CGTGGTGGAGCAGATGTGTGTCACCCAGTATCAGAAGGAGTCCCAGGCCTACTATGACGGGAGGAGATCCTGA"
        )
    },
    "Ratón espinoso PrP": {
        "group": "Roedores",
        "sequence": (
            "AAAAAGCGGCCAAACCCTGGCGGGTGGAACACTGGTGGGAGCCGGTACCCCGGGCAGGGAAGCCCTGGAGGCAACCGTTA"
            "CCCACCTCAGAGTGGTGGCACCTGGGGGCAGCCCCATGGTGGTGGCTGGGGACAACCCCATGGCGGTGGCTGGGGACAGC"
            "CTCATGGCGGTGGCTGGGGTCAGCCCCATGGCGGTGGCTGGGGTCAAGGAGGGGGTACCCATAATCAGTGGAACAAGCCC"
            "AGCAAGCCAAAAACCAACCTCAAGCATGTGGCAGGTGCTGCCGCAGCCGGGGCAGTAGTCGGGGGCCTTGGTGGCTACAT"
            "GTTGGGGAGTGCCATGAGCAGGCCCATGATCCATTTTGGCAACGACTGGGAGGACCGCTACTACCGTGAAAACATGTACC"
            "GTTACCCTAACCAAGTGTACTACAGGCCGGTGGATCAGTATAGCAACCAGAACAACTTCGTGCACGACTGCGTCAACATC"
            "ACCATTAAGCAGCACACGGTCACCACCACCACCAACGGGGAGAACTTCACGGAGACCGACGTGAAGATGATGGAGCGCGT"
            "GGTGGATCAGATGTGTGTCACCCAGTACCATAAGGAGTCCCAGGCCTATTACGACGGGAGGCGATCC"
        )
    },
    "Topillo PrP": {
        "group": "Roedores",
        "sequence": (
            "AAGAAGCGGCCAAAGCCTGGAGGGTGGAACACTGGTGGAAGCCGATACCCTGGGCAGGGCAGCCCTGGAGGCAACCGGTA"
            "CCCACCTCAGGGTGGTGGTACCTGGGGACAGCCCCATGGCGGTGGCTGGGGACAGCCTCACGGTGGTGGTTGGGGTCAGC"
            "CTCACGGTGGCGGTTGGGGTCAACCCCATGGCGGCGGCTGGGGTCAAGGAGGTGGCACCCACAATCAGTGGAACAAGCCC"
            "AGTAAGCCAAAAACCAACATTAAGCATGTGGCAGGCGCTGCCGCGGCTGGGGCAGTGGTGGGGGGCCTGGGTGGCTACAT"
            "GCTGGGGAGCGCCATGAGCAGGCCCATGATCCATTTCGGCAATGACTGGGAGGACCGCTACTACCGTGAAAACATGAACC"
            "GGTACCCTAACCAAGTGTACTACCGGCCGGTGGACCAGTACAACAACCAGAACAACTTCGTGCACGATTGCGTCAACATC"
            "ACCATCAAGCAGCATACAGTCACCACTACCACCAAGGGGGAGAACTTCACGGAGACCGACGTCAAGATGATGGAGCGCGT"
            "GGTGGAGCAGATGTGCGTCACCCAGTATCAGAAGGAGTCCCAGGCCTACTACGAAGGGAGAAGTTCC"
        )
    },

    # ── Murciélagos ─────────────────────────────────────────
    "Murciélago de alas de saco PrP": {
        "group": "Murciélagos",
        "sequence": (
            "AAGAAGCGACCGAAGCCTGGAGGAGGAGGCAGCAGTGGGGGGAGCCGATACCCGGGGCAGGGAAGTCCTGGAGGCAACCG"
            "CTACCCACCCCAGGGCGGTGGCGGCTGGGGACAGCCCCATGGTGGCGGCTGGGGACAGCCCCATGGTGGCGGCTGGGGAC"
            "AGCCCCACGGAGGTGGTGGTTGGGGTCAGCCCCATGGCGGTGGCTGGGGTCAGCCCCATGGTGGCGGAGGCTGGGGTCAA"
            "CCCCATGGTGGCGGAGGCTGGGGTCAAGGTGGTGGCTCCCACAATCAATGGAGCAAGCCCAGTAAGCCGAAAAACAACAT"
            "GAAGCACGTGGCAGGAGCTGCCGCCGCTGGGGCAGTGGTGGGGGGCCTGGGCGGCTACATGCTGGGGAGTGCCATGAGCA"
            "GGCCTGTCATACACTTTGGCAGTGACTATGAGGACCGTTACTATCGTGAAAACATAAACCGTTTCCCCAACCAAGTGTAC"
            "TACAAGCCTGTGGATCAGTACAACAACCAGAACAGCTTTGTGCGCGACTGCGTCAACACCACGGTCAAGCAGCACACGAT"
            "CACCACCACCACCAAGGGGGACAACTTCACCGAGACTGACGTCAAGATCATGGAGCGCGTGGTGGAGGAGATGTGCGTCA"
            "CCCAGTACCAGTACCAGAGAGAAGCTGCTTACCAAAGAGGGGCGAGC"
        )
    },
    "Murciélago de hoja nasal PrP": {
        "group": "Murciélagos",
        "sequence": (
            "ATGGTGAAAAGTCATGTAGGCGGCTGGATCCTGGTTCTCTTTGTGGCCACATGGAGTGACGTGGGCCTCTGCAAGAAGCG"
            "ACCAAAGCCTGGAGGAGGAGGCAGCAGCGGAGGCAGCCGATACCCAGGACAGGGAAGTCCTGGCGGCAACCGCTACCCAC"
            "CCCAGGGTGGTGGCTGGGGTCAGCCCCATGGTGGCGGCTGGGGTCAGCCCCATGGTGGTGGCTGGGGTCAGCCCCATGGT"
            "GGCGGAGGCTGGGGTCAGCCCCATGGTGGCGGAGGCTGGGGTCAGCCCCATGGTGGCGGAGGCTGGGGACAGCCCCATGG"
            "TGGCGGAGGCTGGGGACAGCCCTATGGTGGCAAGCCCAGTAAGCCGAAAACCAACATGAAGCATGTGGCAGGAGCTGCGG"
            "CGGCTGGGGCCGTGGTGGGGGGCCTGGGTGGCTATATGCTGGGGAGTGCTATGAGCAGGCCCCTCATACATTTTGGCAAT"
            "GACTATGAGGACCGTTACTATCGTGAAAACATGAACCGTTTCCCCAACCAAGTGTACTACAAGCCTGTGGATCAGTACAG"
            "CAACCAGAACAACTTCGTGCGCGACTGCGTCAACATCACAGTCAAGGAGCACACGGTCACCACCACCACCAAGGGGGAGA"
            "ACTTCACCGAGACTGATGTCAAGATAATGGAGCGTGTAGTGGAGGAGATGTGCACCATCCAGTACCAGAAAGAGTACCAG"
            "GCTCMTTACCAGAGAGGGGCGAGCGTGATCCTCTTCTCTTCCCCTCCTGTGATCCTCCTCCTCTCTTTCCTCATTTTCCT"
            "AGTCGTGGGATGA"
        )
    },
    "Murciélago frugívoro PrP": {
        "group": "Murciélagos",
        "sequence": (
            "AAGAAACGACCGAAGCCTGGAGGAGGAGGGAGCAGTGGGGGTAGCCGATACCCAGGGCAGGGGAGTCCTGGAGGCAACCG"
            "CTACCCACCCCAGGGTGGTGGTGGCTGGGGCCAGCCCCACGGTGGCGGCTGGGGCCAGCCTCACGGTGGCGGCTGGGGTC"
            "AGCCCCATGGTGGAGGCTGGGGTCAGCCCCACGGTGGTGGCTGGGGACAGCCCCATGGTGGAGGTTGGGGTCAAGGTGGT"
            "GGCACCCACAATCAGTGGAATAAGCCCAGTAAGCCAAAAACCAACCTGAAGCATGTGGCAGGAGCTGCTGCAGCTGGGGC"
            "CGTGGTGGGGGGCCTCGGTGGCTACATGTTGGGAAGTGCAATGAGCAGGCCCATGTTACATTTTGGCAATGACTATGAGG"
            "ATCGTTACTATCGTGAGAACATGTACCGTTACCCCAACCAAGTGTACTACAGGCCCGTGGATCAGTACAGCAACCAGAAC"
            "AGCTTTGTGCATGACTGCGTCAACATCACGGTCAAGCAGCACACGGTCACCACCACCACCAAGGGGGAAAACTTCACTGA"
            "GACCGACGTGAAGATGATGGAGCGCGTGGTGGAGCAGATGTGCATCACCCAGTACCAGCAGGAGTCCCGGGCTGCGTACC"
            "ACAGAGGAGCGAGC"
        )
    },
    "Murciélago orejudo PrP": {
        "group": "Murciélagos",
        "sequence": (
            "AAGAAGCCAAAGACAAGACCCGGAGGGGGATGGAACAGCGGAGGAAGCAACCGCTACCCAGGCCAGCCTGGTAGCCCTGG"
            "AGGCAACCGATACCCTGGCTGGGGGCACCCTCAGGGAGGTGGCACCAATTGGGGTCAGCCCCATCCTGGAGGTTCCAGTT"
            "GGGGTCAGCCCCATGCCGGGGGTTCCAACTGGGGTCAGCCTCATGGTGGATCTAACTGGGGTCAGGGCGGTGGCAGCTAC"
            "GGCAAATGGAAACCAGATAAACCCAAAACCAACCTAAAACATGTAGCTGGGGCTGCTGCTGCTGGGGCAGTTGTGGGAGG"
            "GCTTGGTGGCTACATGCTGGGGAGTGCCATGAGCAGGCCTGTCATGCACTTTGGCAATGAATATGAGGACCGCTACTATC"
            "GTGAAAACCAGTACCGCTACCCCAACCAAGTTATGTACCGGCCCATTGACCAGTACGGCAGCCAGAACAGTTTTGTTCAT"
            "GATTGCGTCAATATCACCGTGAAGCAACACACCACCACCACCACCACCAAAGGGGAGAACTTCACAGAAACTGACATCAA"
            "GATCATGGAGCGTGTGGTCGAGCAGATGTGCATCACACAGTACCAGAATGAGTACCAGGCTGCTCAGCGCTACTACAACA"
            "TG"
        )
    },
    "Murciélago PrP": {
        "group": "Murciélagos",
        "sequence": (
            "ATGAAGAAGCGACCAAAGCCTGGAGGAGGCTGGAACAGTGGGGGGAGCCGATACCCTGGGCAGGGCAGTCCTGGAGGCAA"
            "CCGCTACCCACCCCAGGGCGGTGGCGGCTGGGGTCAGCCCCACGGTGGCGGCTGGGGTCAGCCCCACGGCGGCGGCTGGG"
            "GTCAGCCCCATGGCGGTGGCTGGGGACAGCCCCACGGCGGAGGCTGGGGTCAAGGTGGCACCCACAATCAGTGGAACAAG"
            "CCCAGTAAGCCGAAAACCAACATGAAGCATGTGGCAGGCGCTGCTGCGGCCGGGGCAGTGGTGGGGGGCCTCGGCGGCTA"
            "CATGCTGGGGAGTGCCATGAGCAGGCCCCTCATACATTTTGGCAATGACTATGAGGACCGTTACTATCGTGAAAACATGT"
            "ACCGTTACCCCAACCAAGTGTACTACAGGCCTGTGGATCAGTACAACAACCAGAACAACTTTGTGCATGACTGCGTCAAC"
            "ATCACGATCAAGCAGCACACAGTCACCACCACCACCAAGGGGGAGAACTTCACTGAGACCGACGTCAAGATGATGGAGCG"
            "CGTGGTGGAGCAGATGTGTATCACCCAGTACCAGAAAGAGTACCAGGCTGCTTACCAAGGGAGTGCGAGCTGA"
        )
    },

    # ── Primates ────────────────────────────────────────────
    "Gibón menor PrP": {
        "group": "Primates",
        "sequence": (
            "AAGAAGCGCCCGAAGCCTGGAGGATGGAACACTGGGGGCAGCCGATACCCGGGGCAGGGCAGCCCTGGAGGCAACCGATA"
            "CCCACCTCAGGGCGGTGGCGGCTGGGGGCAGCCTCATGGTGGTGGCTGGGGGCAGCCTCATGGTGGTGGCTGGGGGCAGC"
            "CCCATGGTGGTGGCTGGGGACAGCCTCATGGCGGTGGCTGGGGTCAAGGAGGCGGCACCCACAGTCAGTGGAACAAGCCC"
            "AGTAAGCCAAAAACCAACATGAAGCACATGGCTGGTGCTGCAGCAGCTGGGGCAGTGGTGGGGGGCCTTGGTGGCTACAT"
            "GCTGGGAAGTGCCATGAGCAGGCCCATCATACATTTTGGCAGTGACTATGAGGACCGTTACTATCGTGAAAACATGCACC"
            "GCTACCCCAACCAAGTGTACTATAGGCCCATGGATCAGTACAGCAGCCAGAACAACTTTGTGCACGACTGCGTCAATATC"
            "ACAATCAAGCAGCACACGGTCACCACAACCACCAAAGGGGAGAACTTCACCGAGACCGACGTTAAGATGATGGAGCGCGT"
            "GGTTGAGCAGATGTGTATCACCCAGTACGAGAGGGAATCTCAGGCCTATTACCAGAGAGGATCGAGC"
        )
    },
    "Gibón PrP": {
        "group": "Primates",
        "sequence": (
            "ATGAAGAAGCGCCCGAAGCCTGGAGGATGGAACACTGGGGGCAGCCGATACCCGGGGCAGGGCAGCCCTGGAGGCAACCG"
            "ATACCCACCTCAGGGCGGTGGCGGCTGGGGGCAGCCTCATGGTGGTGGCTGGGGGCAGCCCCATGGTGGTGGCTGGGGGC"
            "AGCCCCATGGTGGTGGCTGGGGACAGCCTCATGGCGGTGGCTGGGGTCAAGGAGGCGGCACCCACAGTCAATGGAACAAG"
            "CCCAGTAAGCCAAAAACCAACATGAAGCACATGGCTGGTGCTGCAGCAGCTGGGGCAGTGGTGGGGGGCCTTGGTGGCTA"
            "CATGCTGGGAAGTGCCATGAGCAGGCCCATCATACATTTTGGCAGTGACTATGAGGACCGTTACTATCGTGAAAACATGC"
            "ACCGCTACCCCAACCAAGTGTACTATAGGCCCATGGATCAGTACAGCAGCCAGAACAACTTTGTGCACGACTGCGTCAAT"
            "ATCACAATCAAGCAGCACACGGTCACCACAACCACCAAAGGGGAGAACTTCACCGAGACCGACGTTAAGATGATGGAGCG"
            "CGTGGTTGAGCAGATGTGTATCACCCAGTACGAGAGGGAATCTCAGGCCTATTACCAGAGAGGATCGAGCTGA"
        )
    },
    "Gálago PrP": {
        "group": "Primates",
        "sequence": (
            "ATGGAGAACCTTGGTTGCTGGATGCTGATTCTCTTTGTGGCCACATGGAGTGACATAGGCCTCTGCAAGAAGCGACCCAA"
            "GCCTGGAGGATGGAACACTGGGGGGAGCCGATACCCGGGCCAGGGCAGCCCTGGAGGCAACCGCTACCCACCCCAGGGTG"
            "GTGGTGGCTGGGGGCAGCCTCACGGTGGCGGCTGGGGGCAGCCCCATGGTGGTGGCTGGGGACAACCCCATGGTGGCGGC"
            "TGGGGACAGCCTCATGGTGGTGGTGGCTGGGGTCAAGGAGGTGGCACCCACAGTCAATGGGGAAAGCCCAGTAAGCCAAA"
            "AACCAACCTGAAGCAGATGGCAGGCGCTGCCGCAGCTGGGGCAGTGGTGGGAGGCCTCGGCGGCTATATGCTGGGGAGTG"
            "CCATGAGCAGGCCCCTCATACATTTTGGCAATGACTATGAGGACCGTTACTATCGTGAAAATATGTACCGTTACCCCAAC"
            "CAAGTGTACTACAGGCCGGTGGATCAGTACAGCAACCAGAACAACTTCGTGCATGACTGCGTCAACATCACGGTCAAGCA"
            "GCACACGGTCACCACCACCACCAAAGGGGAGAACTTCACCGAGACCGATATTAAGATAATGGAGCGTGTGGTTGAGCAGA"
            "TGTGTATCACCCAGTACCAGAAGGAACAGCAGGCTTATTACCAGAGAGGCTCGAGCTTGGCTCTCCTCTCCTCCCCGCCT"
            "GTGATCCTCCTCATCTCC"
        )
    },
    "Lémur PrP": {
        "group": "Primates",
        "sequence": (
            "AAGAAGCGACCAAAGCCTGGAGGAGGCTGGAACACTGGGGGGAGCCGATACCCGGGGCAGGGCAGCCCTGGAGGCAACCG"
            "CTACCCACCCCAGGGCGGTGGCTGGGGGCAGCCTCACGGCGGTGGCTGGGGACAGCCCCATGGTGGCGGCTGGGGACAAC"
            "CCCATGGGGGTGGCTGGGGACAGCCTCATGGTGGTGGCTGGGGTCAAGGAGGTGGCTCCCACGGTCAGTGGAACAAGCCC"
            "AGTAAGCCAAAAACCAACATGAAGCATGTGGCAGGTGCCGCGGCGGCTGGGGCAGTGGTGGGGGGCCTTGGTGGCTACAT"
            "GCTGGGGAGTGCCATGAGCAGGCCCCTCATACATTTTGGCAATGACTATGAGGACCGTTACTATCGCGAAAACATGTACC"
            "GTTACCCCAACCAAGTGTACTACAAACCGGTGGATCAGTACAGCAGCCAGAACAACTTCGTGCACGACTGCGTCAATATC"
            "ACCATCAAGCAGCACACGGTCACCACCACCACCAAAGGGGAGAACTTCACCGAGACCGACGTCAAGATGATGGAGCGCGT"
            "GGTGGAGCAGATGTGTGTCACCCAGTACCAGAGGGAGTACGAGGCTGCCTACCAGAGAGGCTCGAGC"
        )
    },
    "Macaco PrP": {
        "group": "Primates",
        "sequence": (
            "ATGGCGAACCTTGGCTGCTGGATGCTGGTTCTCTTTGTGGCCACATGGAGTGACCTGGGCCTCTGCAAGAAGCGCCCAAA"
            "GCCTGGAGGATGGAACACTGGAGGCAGCCGATACCCGGGGCAGGGCAGCCCTGGAGGCAACCGCTACCCACCCCAGGGTG"
            "GTGGTGGCTGGGGGCAGCCTCATGGTGGTGGCTGGGGGCAACCCCATGGTGGCGGCTGGGGACAGCCTCATGGTGGCGGC"
            "TGGGGACAGCCTCATGGTGGTGGCTGGGGTCAAGGAGGTGGCACCCACAATCAGTGGCACAAGCCCAGTAAGCCAAAAAC"
            "CAGCATGAAGCACATGGCTGGTGCTGCAGCAGCTGGGGCAGTGGTGGGGGGCCTTGGCGGCTACATGCTGGGAAGTGCCA"
            "TGAGCAGGCCCCTCATACATTTTGGCAATGACTATGAGGACCGTTACTATCGTGAAAACATGTACCGTTACCCCAACCAA"
            "GTGTACTACAGGCCTGTGGATCAGTACAGCAACCAGAACAACTTTGTGCACGACTGCGTCAATATCACGATTAAGCAGCA"
            "CACAGTCACCACCACCACCAAAGGGGAGAACTTCACCGAGACCGACGTTAAGATGATGGAGCGCGTGGTTGAGCAGATGT"
            "GTATCACCCAGTACGAGAAGGAATCACAGGCCTATTATCAGAGAGGATCGAGCATGGTCCTCTTCTCCTCCCCGCCTGTG"
            "ATCCTCCTGATTTCTTTCCTCATCTTCCTGATAGTGGGATGA"
        )
    },
    "Tarsero PrP": {
        "group": "Primates",
        "sequence": (
            "ATGGCAAAACTTGGCTACTGGCTGCTGGTTCTCTTTGTGGCCACGTGGAGTGACGTGGGACTCTGCAAGAAGCGACCGAA"
            "GCCTGGAGGCGGAGGAGGATGGAACAGTGGGGGTAGCCGATACCCGGGGCAGGGCAGCCCTGGAGGCAACCGCTATCCAC"
            "CCCAGGGCGGTGGCGGATGGGGGCAGCCCCATGGTGGCGGCTGGGGACAGCCTCATGGTGGCGGCTGGGGACAGCCCCAT"
            "GGTGGTGGCTGGGGACAGCCTCATGGTGGTGGCGGCTGGGGTCAAGGAGGCCAGTGGAGCAAGCCCAGTAAGCCGAAAAC"
            "CAACATGAAGCACGTGGCAGGTGCTGCCGCTGCCGGGGCAGTGGTGGGGGGCCTTGGCGGCTACATGCTGGGGAGTGCCA"
            "TGAGCAGGCCCCTCATACATTTTGGCAATGACTATGAGGACCGTTACTATCGTGAAAACATGTACCGTTACCCCAACCAA"
            "GTGTACTACAGGCCCATGGATCAGTACAACAACCAGAACAACTTTGTGCACGACTGCGTCAATATCACCATCAAGCAGCA"
            "CACGGTTACTACCACCACCAAAGGGGAAAACTTCACCGAGACCGACATTAAGATGATGGAGCGTGTGGTCGAGCAGATGT"
            "GTATCACCCAGTACCAGAAGGAATACCAGGCTTCCTACCACAGTGGATCGAATGTGGTCCTCTTCTCCTCCCCGCCCGTG"
            "ATCCTCCTCATCTCCTTCCTCATCTTCCTGATAGTGGGATGA"
        )
    },

    # ── Marsupiales ─────────────────────────────────────────
    "Bandicoot PrP": {
        "group": "Marsupiales",
        "sequence": (
            "GGAAAAATCCGCTTGGGATATTGGATCTTGGCTCTCTTCGTTGTGACCTGGAGTGATCTAGGTCTCTGTAAGAAACCAAA"
            "GCCAAGACCTGGAGGGGGATGGAACAGTGGAGGAAGCAATCGATACCCAGGCCAGCCAGGTAGCCCTGGAGGCAACCGAT"
            "ATCCTGGCTGGGGGCACCCTCAGGGAGGTGGTACCAATTGGGGTCAGCCCCATCCTGGGGGCTCCAACTGGGGTCAGCCC"
            "CATCCTGGAGGTTCCAGTTGGGGTCAGCCACATGGTGGCTCCAACTGGGGTCAGAGTGGTAGCAATTACAACAACAAGTG"
            "GAAACCAGATAAACCCAAACCCAATCTAAAGCATGTGGCTGGGGCGGCTGCTGCTGGGGCAGTTGTGGGAGGGCTAGGTG"
            "GCTACATGTTGGGGAGTGCCATGAGCAGGCCCATCATGCACTTTGGCAACGAGTATGAAGACCGCTACTACCGTGAAAAC"
            "CAGTACCGCTACCCCAACCAAGTCATGTACCGACCCATTGACCAGTATAGTAACCAGAACAATTTTGTGCATGAC"
        )
    },
    "Canguro PrP": {
        "group": "Marsupiales",
        "sequence": (
            "AAGAAGCCAAAGACAAGACCCGGAGGGGGATGGAACAGCGGAGGAAGCAACCGCTACCCAGGCCAGCCTGGTAGCCCTGG"
            "AGGCAACCGATACCCTGGCTGGGGGCACCCTCAGGGAGGTGGCACCAATTGGGGTCAGCCCCATCCTGGAGGTTCCAGTT"
            "GGGGTCAGCCCCATGCCGGGGGTTCCAACTGGGGTCAGCCTCATGGTGGATCTAACTGGGGTCAGGGCGGTGGCAGCTAC"
            "GGCAAATGGAAACCAGATAAACCCAAAACCAACCTAAAACATGTAGCTGGGGCTGCTGCTGCTGGGGCAGTTGTGGGAGG"
            "GCTTGGTGGCTACATGCTGGGGAGTGCCATGAGCAGGCCTGTCATGCACTTTGGCAATGAATATGAGGACCGCTACTATC"
            "GTGAAAACCAGTACCGCTACCCCAACCAAGTTATGTACCGGCCCATTGACCAGTACGGCAGCCAGAACAGTTTTGTTCAT"
            "GATTGCGTCAATATCACCGTGAAGCAACACACCACCACCACCACCACCAAAGGGGAGAACTTCCCAGAAACTGACATCAA"
            "GATCATGGAGCGTGTGGTCGAGCAGATGTGCATCACACAGTACCAGAATGAGTACCAGGCTGCTCAGCGCTACTACAACA"
            "TG"
        )
    },
    "Dasiúrido PrP": {
        "group": "Marsupiales",
        "sequence": (
            "ATGGGAAAAATCCGCTTGGGATACTGGATCTTGGCTCTCTTCATTGTGACCTGGAGTGACTTGGGCCTCTGTAAGAAACC"
            "AAAACCAAGACCTGGAGGGGGATGGAACAGCGGAGGAAGCAACCGCTACCCAGGCCAGCCCGGTAGTGCCGGAGGCAACC"
            "GATACCCTGGCTGGGGGCACCCTCAGGGAGGTGGCACTAATTGGGGTCAGCCCCATCCTGGGGGTTCCAATTGGGGTCAG"
            "CCCCATGCTGGGGGTTCTAGTTGGGGCCAACCGCATGGTGGATCTAACTGGGGTCAGAGTGGTAGCAGCTACAACCAGAA"
            "GTGGAAACCAGATAAACCCAAAACCAACATGAAACAAATGGCTGGGGCCGCCGCCGCCGGGGCAGTTTTGGGAGGAGTCG"
            "GTGGCTACGTGCTGGGGAGCGCCATGAGCAGGCCTGTCATGCACTTCGGCAATGACTACGAAGACCGCTACTATCGGGAA"
            "AACCAGTACCGCTACCCCAACCAAGTCATGTACCGGCCCATTGACCAGTACAGCAACCAGAACAATTTTGTGCATGACTG"
            "CGTCAACATCACCGTGAAGCAGCACACCACCACCACCACCACCAAGGGGGAGAACTTCACGGAGACGGACATCAAGATCA"
            "TGGAGCGCGTGGTGGAGCAGATGTGCATCACGCAGTACCAGAACGAATACCGCGCCGCCCAGTACAGCTACAACATGGCC"
            "TTCTTCTCGGCCCCGCCCGTGACCCTCCTCCTCCTCAGCTTCCTCATCTTCCTGATTGTGAGCTAA"
        )
    },
    "Falangero PrP": {
        "group": "Marsupiales",
        "sequence": (
            "ATGAAGAAACCAAAGCCAAGACCTGGAGGGGGATGGAACAGCGGAGGAAGCAACCGCTATCCAGGCCAGCCTGGTAGCCC"
            "TGGAGGCAATCGATACCCTGGATGGGGTCAGCCTCATCCTGGAGGTTCCAGTTGGGGTCAGCCCCATGCCGGCGGTTCTA"
            "ATTGGGGTCAGCCCCATGCTGGAGGGTCCAGTTGGGGTCAGCCACATGGTGGATCTAACTGGGGTCAGGCTGGCGGCTAT"
            "AACAAGTGGAAACCAGATAAACCCAAAACCAACCTAAAACATGTGGCTGGGGCCGCTGCTGCTGGGGCAGTTGTAGGAGG"
            "GCTTGGTGGCTACATGCTGGGGAGTGCCATGAGTAGGCCTGTCATGCACTTTGGTAATGAATATGAAGACCGCTACTATC"
            "GTGAAAACCAGTACCGCTACCCCAACCAAGTTATGTACCGGCCCATTGACCAGTACAGCAGCCAGAGCAACTTTGTGCAC"
            "GACTGCGTCAACATCACGGTGAAACAACATACCACCACCACCACCACCAAAGGGGAGAACTTCACGGAAACCGATATCAA"
            "AATCATGGAGCGTGTGGTCGAGCAGATGTGCATCACGCAGTACCAGAATGAGTACCAGGCTGCCGCCCAGCGCGGCTACA"
            "ACTAA"
        )
    },
    "Tigre de Tasmania PrP": {
        "group": "Marsupiales",
        "sequence": (
            "ATGGGAAAAATCTGCTTGGGATACTGGATCTTGGCTCTCTTTATTGTGACCTGGAGTGATTTAGGCCTCTGTAAGAAACC"
            "AAAACCAAGACCCGGAGGGGGATGGAACAGCGGAGGAAGCAACCGCTATCCAGGCCAGCCCGGTAGCGCTGGAGGCAACC"
            "GATACCCTGGTTGGGGGCACCCTCAGGGAGGTGGCACTAATTGGGGTCAGCCCCATCCTGGGGGTTCCAGTTGGGGTCAG"
            "CCCCATGCTGGGGGTTCTAATTGGGGTCAACCGCATGGTGGATCAAACTGGGGTCAGAGTGGTAGCAGCTACAACCAGAA"
            "GTGGAAACCAGATAAACCCAAAACCAACATGAAACATGTGGCTGGGGCCGCTGCTGCTGGGGCAGTTGTGGGAGGACTTG"
            "GTGGCTACATGCTGGGGAGTGCCATGAGCCGGCCCATCATGCACTTTGGCAATGAGTACGAAGACCGCTACTATCGTGAA"
            "AACCAGTACCGCTACCCCAACCAAGTCATGTACCGGCCCATTGACCAGTACAGCAACCAGAACAATTTTGTGCACGACTG"
            "CGTCAATATTACCGTGAAGCAGCACACCACCACCACCACCCCCCAAGGGGAGAACTTCACAGAGACGGATATCAAGATCA"
            "TGGAACGCGTGGTGGAGCAGATGTGCATCACGCAGTACCAGACCGAGTACCGTGCCGCCCAGTACACCTACAACATGGCG"
            "TTCTTCTCGGCCCCGCCAGTGACCCTCCTCCTCCTCAGCTTCCTTATTTTCCTGATTGTGAGCTAA"
        )
    },
    "Ualabí liebre PrP": {
        "group": "Marsupiales",
        "sequence": (
            "AAAAAGCGGCCAAACCCTGGCGGGTGGAACACTGGTGGGAGCCGGTACCCCGGGCAGGGAAGCCCTGGAGGCAACCGTTA"
            "CCCACCTCAGAGTGGTGGCACCTGGGGGCAGCCCCATGGTGGTGGCTGGGGACAACCCCATGGCGGTGGCTGGGGACAGC"
            "CTCATGGCGGTGGCTGGGGTCAGCCCCATGGCGGTGGCTGGGGTCAAGGAGGGGGTACCCATAATCAGTGGAACAAGCCC"
            "AGCAAGCCAAAAACCAACCTCAAGCATGTGGCAGGTGCTGCCGCAGCCGGGGCAGTAGTCGGGGGCCTTGGTGGCTACAT"
            "GTTGGGGAGTGCCATGAGCAGGCCCATGATCCATTTTGGCAACGACTGGGAGGACCGCTACTACCGTGAAAACATGTACC"
            "GTTACCCTAACCAAGTGTACTACAGGCCGGTGGATCAGTATAGCAACCAGAACAACTTCGTGCACGACTGCGTCAACATC"
            "ACCATTAAGCAGCACACGGTCACCACCACCACCAACGGGGAGAACTTCACGGAGACCGACGTGAAGATGATGGAGCGCGT"
            "GGTGGATCAGATGTGTGTCACCCAGTACCATAAGGAGTCCCAGGCCTATTACGACGGGAGGCGATCC"
        )
    },

    # ── Artiodáctilos ───────────────────────────────────────
    "Ballena PrP": {
        "group": "Artiodáctilos",
        "sequence": (
            "ACGTGCAGTGACATGGGCCTCTGCAAGAAGCGACCAAAGCCTGGAGGAGGATGGAACACTGGGGGGAGCCGATACCCAGG"
            "ACAGGGCAGTCCTGGAGGCAACCGCTATCCACCCCAGGGAGGGGGAGGCTGGGGTCAGCCCCACGGTGGTGGCTGGGGCC"
            "AACCCCACGGTGGTGGCTGGGGTCAGCCCCACGGTGGTGGCTGGGGTCAGCCCCATGGTGGCGGAGGCTGGGGTCAAGGT"
            "GGTGGCACCCACAATCAGTGGAAGCCCAGTAAGCCGAAAACCAACATGAAGCATGTGGCAGGAGCTGCTGCAGCTGGGGC"
            "GGTGGTAGGGGGCCTTGGTGGCTACATGCTGGGGAGTGCCATGAGCAGGCCCCTTATACATTTTGGCAGTGACTATGAGG"
            "ACCGTTACTATCGTGAAAACATGTACCGTTACCCCAGCCAGGTATACTACAGGCCAGTGGATCAGTATAACAGCCAGAAC"
            "AGCTTTGTGCATGACTGCGTCAACATCACAGTCAAGCAGCACACAGTCACTACCACCACCACCAAGGGGGAGAACTTCAC"
            "TGAGACGGACATCAAGATGATGGAGCGTGTGGTGGAGCAAATGTGCATCACCCAGTACCAGAGAGAATACCAGGCTTATT"
            "ACCAAAGAGGAGCAAGTGTGATCCTCTTCTCCTCCCCTCCTGTG"
        )
    },
    "Búfalo PrP": {
        "group": "Artiodáctilos",
        "sequence": (
            "GTGAAAAGACACATAGGCAGTTGGATCCTGGTTCCCTTTGTGGTCATGTGGAGTGACGTGGGCCTCTGCAAGAAGCGACC"
            "AAAACCTGGAGGAGGATGGAACACTGGGGGGAGCCGATACCCAGGACAGGGCAGTCCTGGAGGCAACCGTTATCCATCTC"
            "AGGGAGGGGGTGGCTGGGGTCAGCCCCATGGAGGTGGCTGGGGCCAGCCTCATGGAGGTGGCTGGGGCCAGCCTCATGGA"
            "GGTGGCTGGGGTCAGCCGCATGGTGGTGGCTGGGGACAGCCGCATGGTGGTGGAGGCTGGGGTCAAGGTGGTACCCACAG"
            "TCAATGGAACAAGCCCAGTAAGCCAAAAACCAACATGAAGCATATGGCAGGAGCTGCTGCAGCTGGAGCAGTGGTAGGGG"
            "GCCTTGGTGGCTACATGCTGGGAAGTGCCATGAGCAGGCCTCTTATACATTTTGGTAATGACTATGAGGACCGTTACTAT"
            "CGTGAAAACATGCACCGTTACCCCAACCAAGTGTACTACAGGCCAGTGGATCAGTATAGTAACCGGAACAACTTTGTGCA"
            "TGACTGTGTCAACATCACAGTCAAGGAACACACAGTCACCACCACCACCAAGGGGGAGAACTTCACCGAAACTGACATCA"
            "AGATGATGGAGCGAGTGGTGGAGCAAATGTGCATCACCCAGTACCAGAGAGAATCCCAGGCTTATTACCAACGAGGGGCA"
            "AGTGTGATCCTCTTCTCTTCCCCTCCTGTGATCCTCCTCATCTCTTTGCTCATTTTTCTCATAGTAGGA"
        )
    },
    "Cerdo PrP": {
        "group": "Artiodáctilos",
        "sequence": (
            "AAGAAGCGACCAAAGCCTGGCGGAGGATGGAACACTGGGGGGAGCCGATACCCAGGGCAGGGTAGTCCTGGAGGCAACCG"
            "CTATCCACCCCAGGGAGGGGGCGGCTGGGGACAGCCCCATGGAGGTGGCTGGGGACAGCCCCACGGAGGTGGTTGGGGAC"
            "AGCCCCATGGTGGTGGCTGGGGACAGCCCCATGGTGGCGGAGGCTGGGGTCAAGGTGGTGGCTCCCACGGTCAGTGGAAC"
            "AAGCCCAGTAAGCCGAAAACCAACATGAAGCATGTGGCAGGTGCCGCTGCAGCTGGGGCAGTGGTAGGGGGCCTCGGCGG"
            "TTACATGCTGGGGAGTGCCATGAACAGACCCCTGATACATTTTGGCAGTGACTATGAGGACCGTTACTATCGTGAAAACA"
            "TGTACCGTTACCCCAACCAAGTGTACTACAGGCCAGTGGATCAGTACAGCAACCAAAACAGTTTTGTGCATGACTGCGTC"
            "AACATCACCGTCAAGCAGCACACAGTCACCACAACCACCAAGGGGGAGAACTTCACCGAGACCGACGTCAAGATGATAGA"
            "GCGCGTGGTGGAACAGATGTGCATCACCCAGTACCAGAAAGAGTACGAGGCTTACGCCCAAAGAGGGGCAAGT"
        )
    },
    "Ciervo PrP": {
        "group": "Artiodáctilos",
        "sequence": (
            "AAAAAGCGGCCAAACCCTGGCGGGTGGAACACTGGTGGGAGCCGGTACCCCGGGCAGGGAAGCCCTGGAGGCAACCGTTA"
            "CCCACCTCAGAGTGGTGGCACCTGGGGGCAGCCCCATGGTGGTGGCTGGGGACAACCCCATGGCGGTGGCTGGGGACAGC"
            "CTCATGGCGGTGGCTGGGGTCAGCCCCATGGCGGTGGCTGGGGTCAAGGAGGGGGTACCCATAATCAGTGGAACAAGCCC"
            "AGCAAGCCAAAAACCAACCTCAAGCATGTGGCAGGTGCTGCCGCAGCCGGGGCAGTAGTCGGGGGCCTTGGTGGCTACAT"
            "GTTGGGGAGTGCCATGAGCAGGCCCATGATCCATTTTGGCAACGACTGGGAGGACCGCTACTACCGTGAAAACATGTACC"
            "GTTACCCTAACCAAGTGTACTACAGGCCGGTGGATCAGTATAGCAACCAGAACAACTTCGTGCACGACTGCGTCAACATC"
            "ACCATTAAGCAGCACACGGTCACCACCACCACCAACGGGGAGAACTTCACGGAGACCGACGTGAAGATGATGGAGCGCGT"
            "GGTGGATCAGATGTGTGTCACCCAGTACCATAAGGAGTCCCAGGCCTATTACGACGGGAGGCGATCC"
        )
    },
    "Muntíaco PrP": {
        "group": "Artiodáctilos",
        "sequence": (
            "ATGAAGAAGCGGCCGAAGCCTGGAGGAGGCTGGAACACCGGGGGGAGCCGATACCCAGGGCAGGGCAGTCCTGGAGGCAA"
            "CCGCTACCCACCCCAGGGCGGTGGTGGCTGGGGCCAGCCCCACGGGGGCGGCTGGGGCCAGCCCCATGGGGGTGGCTGGG"
            "GTCAGCCCCACGGGGGCGGCTGGGGACAGCCGCATGGTGGCGGTGGCTGGGGTCAAGGTGGTGGCAGCCACGGTCAGTGG"
            "GGCAAGCCCAGTAAGCCCAAAACCAACATGAAGCATGTGGCGGGAGCCGCGGCAGCCGGGGCGGTTGTGGGGGGCCTGGG"
            "CGGCTACATGCTGGGGAGCGCCATGAGCAGGCCCCTCATTCATTTTGGCAACGACTATGAGGACCGCTACTACCGTGAGA"
            "ACATGCACCGCTACCCCGACCAAGTGTACTACAAGCCGGTGGATCAGTACAGCAACCAGAACAACTTCGTGCACGACTGC"
            "GTCAACATCACGGTCAAGCAGCACACGGTGACCACCACCACCAAGGGCGAGAACTTCACGGAGACCGACATGAAGATCAT"
            "GGAGCGCGTGGTGGAGCAGATGTGTGTCACCCAGTACCAGCGAGAGTCTGAGGCTTACTACCAGAGGGGGGCGAGCTAA"
        )
    },
    "Oveja PrP": {
        "group": "Artiodáctilos",
        "sequence": (
            "ATGAAGAAGCGACCAAAACCTGGCGGAGGATGGAACACTGGGGGGAGCCGATACCCGGGACAGGGCAGTCCTGGAGGCAA"
            "CCGCTATCCACCTCAGGGAGGGGGTGGCTGGGGTCAGCCCCATGGAGGTGGCTGGGGCCAACCTCATGGAGGTGGCTGGG"
            "GTCAGCCCCATGGTGGTGGCTGGGGACAGCCACATGGTGGTGGAGGCTGGGGTCAAGGTGGTAGCCACAGTCAGTGGAAC"
            "AAGCCCAGTAAGCCAAAAACCAACATGAAGCATGTGGCAGGAGCTGCTGCAGCTGGAGCAGTGGTAGGGGGCCTTGGTGG"
            "CTACATGCTGGGAAGTGCCATGAGCAGGCCTCTTATACATTTTGGCAATGACTATGAGGACCGTTACTATCGTGAAAACA"
            "TGTACCGTTACCCCAACCAAGTGTACTACAGACCAGTGGATCAGTATAGTAACCAGAACAACTTTGTGCATGACTGTGTC"
            "AACATCACAGTCAAGCAACACACAGTCACCACCACCACCAAGGGGGAGAACTTCACCGAAACTGACATCAAGATAATGGA"
            "GCGAGTGGTGGAGCAAATGTGCATCACCCAGTACCAGAGAGAATCCCAGGCTTATTACCAAAGGGGGGCAAGTTAG"
        )
    },

    # ── Carnívoros ──────────────────────────────────────────
    "Gato PrP": {
        "group": "Carnívoros",
        "sequence": (
            "AAGAAGCGGCCGAAGCCTGGTGGAGGATGGAACACTGGGGGGAGCCGGTACCCGGGGCAGGGCAGTCCTGGAGGCAACCG"
            "TTACCCACCCCAGGGCGGTGGCGGCTGGGGTCAGCCCCACGCCGGCGGCGGCTGGGGTCAGCCCCACGCCGGCGGAGGCT"
            "GGGGTCAGCCCCACGCCGGCGGTGGCTGGGGTCAGCCCCACGCCGGCGGCGGCTGGGGTCAAGGTGGTGGCACCCACGGT"
            "CAGTGGGGCAAACCCAGTAAGCCGAAAACCAACATGAAGCACATGGCCGGAGCCGCGGCAGCCGGGGCGGTAGTGGGGGG"
            "CCTCGGCGGCTACATGCTGGGGAGTGCCATGAGCCGGCCCCTCATTCATTTTGGCAACGACTACGAGGACCGTTACTACC"
            "GTGAAAACATGTACCGCTACCCCAACCAAGTGTACTACAGGCCAGTGGATCAGTACAGCAACCAGAACAACTTTGTGCAC"
            "GACTGCGTCAACATCACGGTCAGGCAGCACACGGTCACCACCACCACCAAGGGGGAGAACTTCACGGAGACCGACATGAA"
            "GATAATGGAGCGCGTGGTGGAGCAGATGTGCGTCACCCAGTACCAGAAAGAGTCCGAGGCCTACTACCAAAGAGGGGCGA"
            "GC"
        )
    },
    "Marta PrP": {
        "group": "Carnívoros",
        "sequence": (
            "AAGAAGCGGCCGAAGCCTGGAGGAGGCTGGAACACCGGGGGGAGCCGATACCCAGGGCAGGGCAGTCCTGGAGGCAACCG"
            "CTACCCACCCCAGGGCGGTGGTGGCTGGGGCCAGCCCCACGGGGGTGGCTGGGGACAGCCCCATGGGGGTGGCTGGGGTC"
            "AGCCCCACGGGGGCGGCTGGGGACAGCCGCATGGTGGTGGTGGCTGGGGTCAAGGTGGTGGCAGCCACGGTCAGTGGGGC"
            "AAGCCCAGTAAGCCCAAAACCAACATGAAGCATGTGGCGGGAGCCGCGGCAGCCGGGGCGGTTGTGGGGGGCCTGGGCGG"
            "CTACATGCTGGGGAGCGCCATGAGCAGGCCCCTCATTCATTTTGGCAACGACTATGAGGACCGCTACTACCGTGAGAACA"
            "TGCACCGCTACCCCGACCAAGTGTACTACAAGCCGGTGGATCAGTACAGCAACCAGAACAACTTCGTGCACGACTGCGTC"
            "AACATCACGGTCAAGCAGCACACGGTGACCACCACCACCAAGGGCGAGAACTTCACGGAGACCGACATGAAGATCATGGA"
            "GCGCGTGGTGGAGCAGATGTGTGTCACCCAGTACCAGCGAGAGTCTGAGGCTTACTACCAGAGGGGGGCGAGC"
        )
    },
    "Oso PrP": {
        "group": "Carnívoros",
        "sequence": (
            "ATGGTGAAAAGCCACATAGGCGGCTGGATCCTGGTTCTCTTTGTGGCCACGTGGAGTGACGTGGGCCTCTGCAAGAAGCG"
            "GCCGAAGCCTGGAGGCGGCTGGAACACCGGGGGGAGCCGATACCCAGGGCAGGGCAGTCCCGGAGGCAACCGCTACCCAC"
            "CCCAGGGCGGCGGCGGCTGGGGTCAGCCCCACGGGGGCGGCTGGGGACAGCCCCATGGGGGTGGCTGGGGTCAGCCCCAC"
            "GGGGGCGGTTGGGGACAGCCCCACGGGGGCGGTGGCTGGGGTCAAGGCGGGGGCGGCCACGGTCAGTGGGGCAAGCCCAG"
            "TAAGCCCAAAACCAACATGAAGCACGTGGCGGGAGCCGCGGCAGCGGGGGCGGTCGTGGGGGGCCTCGGCGGCTACATGC"
            "TGGGGAGCGCCATGAGCCGGCCCCTCATTCATTTTGGCAACGACTATGAGGACCGTTACTACCGTGAGAACATGTACCGC"
            "TACCCCAACCAAGTGTACTACAAGCCGGTGGATCAGTACAGCAACCAGAACAGCTTCGTGCACGACTGCGTCAACATCAC"
            "GGTCAAGCAGCACACGGTCACCACCACCACCAAGGGGGAGAACTTCACGGAGACCGACATAAAGATCATGGAGCGCGTGG"
            "TGGAGCAGATGTGCGTCACCCAGTACCAGAGAGAGGCCGAGGCTTACTACCAAAGGGGGGCGAGCGCCATCCTCTTCTCC"
            "CCGCCCCCGGTGATCCTCCTCATCTCGCTGCTCATTCTCCTGATCGTTGGATGA"
        )
    },

    # ── Lagomorfos ──────────────────────────────────────────
    "Conejo PrP": {
        "group": "Lagomorfos",
        "sequence": (
            "ATGGCGCACCTCGGCTACTGGATGCTGCTTCTCTTTGTGGCCGCATGGAGTGACGTGGGCCTCTGCAAGAAGCGGCCGAA"
            "GCCTGGAGGAGGATGGAACACAGGGGGGAGCCGGTACCCGGGTCAGGGCAGCCCTGGAGGCAACCGCTACCCGCCCCAGG"
            "GCGGCGGCTGGGGGCAACCCCACGGTGGCGGCTGGGGGCAGCCTCACGGAGGTGGCTGGGGGCAGCCCCACGGCGGTGGC"
            "TGGGGGCAGCCCCACGGTGGTGGCTGGGGTCAAGGAGGTACCCACAACCAGTGGGGCAAGCCCAGTAAGCCGAAAACCAG"
            "CATGAAGCACGTGGCCGGGGCGGCGGCGGCCGGGGCGGTGGTGGGGGGCCTCGGTGGCTACATGCTGGGGAGCGCCATGA"
            "GCAGGCCCCTCATCCACTTCGGCAACGACTACGAGGACCGCTACTACCGGGAGAACATGTACCGGTACCCCAACCAGGTG"
            "TACTACAGGCCCGTGGACCAGTACAGCAACCAGAACAGCTTCGTGCACGACTGCGTCAACATCACGGTGAAGCAGCACAC"
            "GGTGACCACCACCACCAAAGGGGAGAACTTCACTGAGACCGACATCAAGATCATGGAGCGCGTGGTGGAGCAAATGTGCA"
            "TCACACAGTACCAGCAGGAGTACCAGGCCGCCTACCAGAGGGCGGCCGGCGTGCTGCTCTTCTCCTCGCCGCCCGTCATC"
            "CTCCTCATCTCCTTCCTCATCTTCCTGATGGTGGGA"
        )
    },
    "Liebre PrP": {
        "group": "Lagomorfos",
        "sequence": (
            "ATGGCGCACCTCGGCTACTGGATGCTGCTTCTCTTTGTGGCCGCATGGAGTGACGTGGGCCTCTGCAAGAAGCGGCCGAA"
            "GCCTGGAGGAGGATGGAACACAGGGGGGAGCCGGTACCCGGGTCAGGGCAGCCCTGGAGGCAACCGCTACCCGCCCCAGG"
            "GCGGCGGCTGGGGGCAACCCCACGGTGGCGGCTGGGGGCAGCCTCACGGAGGTGGCTGGGGGCAGCCCCACGGCGGTGGC"
            "TGGGGGCAGCCCCACGGTGGTGGCTGGGGTCAAGGAGGTACCCACAACCAGTGGGGCAAGCCCAGTAAGCCGAAAACCAG"
            "CATGAAGCACGTGGCCGGGGCGGCGGCGGCCGGGGCGGTGGTGGGGGGCCTCGGCGGCTACATGCTGGGGAGCGCCATGA"
            "GCAGGCCCCTCATCCACTTCGGCAACGACTACGAGGACCGCTACTACCGGGAGAACATGTACCGGTACCCCAACCAGGTG"
            "TACTACAGGCCCGTGGACCAGTACAGCAACCAGAACAGCTTCGTGCACGACTGCGTCAACATCACGGTGAAGCAGCACAC"
            "GGTGACCACCACCACCAAAGGGGAGAACTTCACCGAGACCGACATCAAGATCATGGAGCGCGTGGTGGAGCAAATGTGCA"
            "TCACACAGTACCAGCAGGAGTACCAGGCCGCCTACCAGAGGGCGGCCGGCGCGCTGCTCTTCTCCTCGCCACCCGTCATC"
            "CTCCTCATCTCCTTCCTCATCTTCCTGATCGTGGGATGA"
        )
    },

    # ── Otros ───────────────────────────────────────────────
    "Elefante PrP": {
        "group": "Otros",
        "sequence": (
            "AAGAAGCGACCAAAGCCTGGAGGAGGATGGAACACTGGGGGAAGCCGATACCCGGGGCAGGGGAGTCCTGGAGGCAACCG"
            "CTACCCACCTCAGGGTGGTGGTGGCTGGGGTCAGCCTCACGGTGGCGGCTGGGGACAGCCCCATGGTGGTGGCGGCTGGG"
            "GTCAGCCCCACGGTGGTGGCTGGGGACAGCCCCATGGTGGTGGTGGCTGGGGTCAAGGTAGCTCCCATAGTCAGTGGAAC"
            "AAGCCCAGTAAGCCAAAAACCAACTTGAAGCATGTGGCAGGGGCTGCTGCAGCTGGGGCAGTAGTGGGGGGCCTTGGTGG"
            "CTACATGCTGGGAAGCGCCATGAGCAGGCCTCTCATACATTTTGGTAACGACTATGAGGACCGTTACTACCGTGAAAACA"
            "TGTACCGTTACCCCAACCAAGTGTACTACAGGCCCGTGAATGAGTACAGCAACGAGAACAACTTCGTGCACGACTGCGTC"
            "AACATTACAGTCAAGCAGCACACGACCACCACCATCACCAAGGGGGAGAACTTCACTGAGACCGATACCAAGATAATGGA"
            "GCGCATGGTCGAGCAGATGTGCGTAACCCAGTACCGCAAAGAATTCCAGGCTTACCAGAGAGGGTCGAGC"
        )
    },
    "Musaraña PrP": {
        "group": "Otros",
        "sequence": (
            "ATGGTGACGGGCCACCTAGGATGCTGGCTCCTGGTCCTCTTCATGGCCACCTGGAGTGACGTGGGCCTGTGCAAGAAGAG"
            "GCCGAAGCCCGGCGGAACCTGGAACTCTGGGGGGAGTCGGTATCCAGGCCAGGGCGGTTATGGGGGCAACCGCTACCCAC"
            "CCCAGGGAGGCGGAGGCTGGGGTCAGCCCCATGGGGGTGGAGGCTGGGGTCAGCCCCATGGCGGCGGAGGCTGGGGTCAG"
            "CCCCACGGGGGTGGAGGCTGGGGTCAGCCCCACGGTGGAGGCTGGGGCCAAGGCTCCCACAACCAGTGGAATAAGCCCAG"
            "CAAGCCCAAGACCAACATGAAGCACGTGGCCGGGGCGGCGGCGGCCGGGGCGGTCGTGGGGGGCCTGGGCGGCTACATGC"
            "TGGGGAGTGCCATGAGCCGGCCCCTCATGCACTTCGGCAACGACTACGAGGACCGGTACTACCGTGAGAACATGTACCGC"
            "TACCCCAACCAAGTGTACTACAAGCCGGTGGACCAGTACAGCAACCAGAACAACTTCGTGCACGACTGCGTGAACATGAC"
            "CGTCAAGCAGCACACGGTCACCACCACCAGCAAGGGCGAGAACTTCACCGAGACCGACGTCAAGATCATGGAGCGCGTGG"
            "TGGAGCAGATGTGCATCACCCAGTACCGCGAGGCAGCCCAGGCCTCCTACCTGCAGGGGGACAGCACAGTCCTCTTCTCC"
            "TCCCCGCCCTTCATCCTGCTCATCTCCTTCCTCATCTTCCTGATCGTGGGATGA"
        )
    },
}
