"""
PrP reference sequences for PRNP-OrthoMiner.
Sequences stored as uppercase nucleotide strings without whitespace.
"""

GROUPS_ORDER = [
    "Roedores", "Murciélagos", "Primates",
    "Marsupiales", "Artiodcátilos", "Carnívoros", "Lagomorfos", "Otros"
]

PRP_SEQUENCES = {
    "Ratón espinoso PrP": {
        "group": "Roedores",
        "sequence": (
            "AAAAAGCGGCCAAACCCTGGCGGGTGGAACACTGGTGGGAGCCGGTACCCCGGGCAGGGAAGCCCTGGAGGCAACCGTTA"
            "CCCACCTCAGAGTGGTGGCACCTGGGGGCAGCCCCATGGTGGTGGCTGGGGACAACCCCATGGCGGTGGCTGGGGACAGC"
            "CTCATGGCGGTGGCTGGGGTCAGCCCCATGGCGGTGGCTGGGGTCAAGGAGGGGGTACCCATAATCAGTGGAACAAGCCC"
            "AGCAAGCCAAAAACCAACCTCAAGCATGTGGCAGGTGCTGCCGCAGCCGGGGCAGTAGTCGGGGGCCTTGGTGGCTACAT"
            "GTTGGGGAGTGCCATGAGCAGGCCCATGATCCATTTTGGCAACGACTGGGAGGACCGCTACTACCGTGAAAACATGTACC"
            "GTTACCCTAACCAAGTGTACTACAGGCCGGTGGATCAGTATAGCAACCAGAACAACTTCGTGCACGACTGCGTCAACATC"
            "ACCATTAAGCAGCACACGGTCACCACCACCACCAACGGGGAGAACTTCACGGAGACCGACGTGAAGATGATGGAGCGCGT"
            "GGTGGATCAGATGTGTGTCACCCAGTACCATAAGGAGTCCCAGGCCTATTACGACGGGAGGCGATCC"
        )
    }
    # → Añadir más secuencias aquí en siguientes etapas
}
