"""
PrP reference sequences for PRNP-OrthoMiner.
Sequences stored as uppercase nucleotide strings without whitespace.
"""

PRP_SEQUENCES = {
    "Ratón espinoso PrP": {
        "group": "Roedores",
        "sequence": "AAAAAGCGGCCAAACCCTGGCGGGTGGAACACTGGTGGGAGCCGGTACCCCGGGCAGGGAAGCCCTGGAGGCAACCGTTACCCACCTCAGAGTGGTGGCACCTGGGGGCAGCCCCATGGTGGTGGCTGGGGACAACCCCATGGCGGTGGCTGGGGACAGCCTCATGGCGGTGGCTGGGGTCAGCCCCATGGCGGTGGCTGGGGTCAAGGAGGGGGTACCCATAATCAGTGGAACAAGCCCAGCAAGCCAAAAACCAACCTCAAGCATGTGGCAGGTGCTGCCGCAGCCGGGGCAGTAGTCGGGGGCCTTGGTGGCTACATGTTGGGGAGTGCCATGAGCAGGCCCATGATCCATTTTGGCAACGACTGGGAGGACCGCTACTACCGTGAAAACATGTACCGTTACCCTAACCAAGTGTACTACAGGCCGGTGGATCAGTATAGCAACCAGAACAACTTCGTGCACGACTGCGTCAACATCACCATTAAGCAGCACACGGTCACCACCACCACCAACGGGGAGAACTTCACGGAGACCGACGTGAAGATGATGGAGCGCGTGGTGGATCAGATGTGTGTCACCCAGTACCATAAGGAGTCCCAGGCCTATTACGACGGGAGGCGATCC"
    }
}

GROUPS_ORDER = ["Roedores", "Murciélagos", "Primates", "Marsupiales", "Artiodáctilos", "Carnívoros", "Lagomorfos", "Otros"]
